buildscript {
    repositories {
        mavenLocal()
        maven {
            url = "https://repo.grails.org/grails/core"
        }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}

version = "5.0.0-SNAPSHOT"
group = "org.grails.plugins"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: 'org.apache.grails.gradle.grails-publish'

compileJava.options.release = 17

repositories {
    mavenLocal()
    maven {
        url = "https://repo.grails.org/grails/core"
    }
}

configurations {
    documentation
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:${grailsVersion}")

    compileOnly 'org.springframework.boot:spring-boot-starter-logging'
    compileOnly "org.springframework.boot:spring-boot-starter-actuator"
    compileOnly "org.springframework.boot:spring-boot-autoconfigure"
    compileOnly "org.springframework.boot:spring-boot-starter-tomcat"

    compileOnly "org.apache.grails:grails-web-boot"
    compileOnly "org.apache.grails:grails-dependencies-starter-web"
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    profile "org.apache.grails.profiles:plugin"

    testImplementation "org.apache.grails:grails-testing-support-web"

    console "org.apache.grails:grails-console"

    implementation "org.apache.grails:grails-cache"
    implementation "org.ehcache:ehcache", {
        capabilities {
            requireCapability('org.ehcache:ehcache-jakarta')
        }
    }

    documentation "org.apache.groovy:groovy-all:4.0.29"
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
}

grailsPublish {
    githubSlug = 'grails-plugins/grails-cache-ehcache'
    license {
        name = 'Apache-2.0'
    }
    title = "Grails Cache Ehcache Plugin"
    desc = "Provides an ehcache implementation of the cache plugin"
    developers = [jameskleeh: "James Kleeh"]
}

apply from: layout.projectDirectory.file('gradle/docs-config.gradle')
